apiVersion: apps/v1
kind: Deployment
metadata:
  name: decase-ai
  namespace: sk-team-08
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decase-ai
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/health"
        update: ef57a0bd58aa0a2935ada6f903c3b5f5
      labels:
        app: decase-ai
    spec:
      containers:
        - name: decase-ai
          image: amdp-registry.skala-ai.com/skala25a/sk-team-08-decase-ai:1.0.0-22-10f91e15588f
          imagePullPolicy: Always

          # 볼륨 마운트 설정
          volumeMounts:
            # 파일 스토리지 경로들
            - name: storage-volume
              mountPath: /app/docs # 기본 docs 디렉터리

          env:
            - name: LOGGING_LEVEL
              value: DEBUG
            - name: USER_NAME
              value: sk-team-08
            - name: NAMESPACE
              value: sk-team-08
            # DB 설정
            - name: MARIA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ai-secret
                  key: MARIA_PASSWORD
            - name: MARIA_USER
              valueFrom:
                secretKeyRef:
                  name: ai-secret
                  key: MARIA_USER
            - name: MARIA_HOST
              valueFrom:
                secretKeyRef:
                  name: ai-secret
                  key: MARIA_HOST
            - name: MARIA_PORT
              valueFrom:
                secretKeyRef:
                  name: ai-secret
                  key: MARIA_PORT
            - name: MARIA_NAME
              valueFrom:
                secretKeyRef:
                  name: ai-secret
                  key: MARIA_NAME
            # api key 설정
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-secret # 이거 ai secret이라고 써잇던데 decase-secret이 맞지않나..?
                  key: OPENAI_API_KEY
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-secret
                  key: ANTHROPIC_API_KEY
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-secret
                  key: GOOGLE_API_KEY
            # 파일 스토리지 경로 설정
            - name: FILE_STORAGE_PATH_UPLOADS
              value: "/app/docs/uploads" # 볼륨 마운트 경로로 설정
            - name: FILE_STORAGE_PATH_SRS
              value: "/app/docs/srs" # 볼륨 마운트 경로로 설정
            - name: FILE_STORAGE_PATH_ASIS
              value: "/app/docs/asis" # 볼륨 마운트 경로로 설정
            - name: FILE_STORAGE_PATH_MOCKUP
              value: "/app/docs/mockup" # 볼륨 마운트 경로로 설정
      # 단순 볼륨 설정
      volumes:
        - name: storage-volume
          hostPath:
            path: /var/lib/decase-ai-storage
            type: DirectoryOrCreate # 기본 디렉터리만 자동 생성
